services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: ahmedther/ask-me-ai:backend-latest
    container_name: ask_me_backend_container
    env_file:
      - /backend/.env
    depends_on:
      - redis

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    image: ahmedther/ask-me-ai:nginx-latest
    container_name: ask_me_nginx_container
    env_file:
      - /nginx/.env
    ports:
      - 80:80
      - 3000:3000
    depends_on:
      - backend

  redis:
    build:
      context: ./redis
      dockerfile: ./Dockerfile
    image: ahmedther/ask-me-ai:redis-latest
    container_name: ask_me_redis_container
