apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: ask-me-ai
    tier: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ask-me-ai
      tier: nginx
  template:
    metadata:
      labels:
        app: ask-me-ai
        tier: nginx
    spec:
      containers:
        - name: nginx
          image: ahmedther/ask-me-ai:nginx-latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: nginx-config
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
