apiVersion: v1
kind: Service
metadata:
  # name: backend-service
  # Ideally the name should be backend-service but inorder to troubleshoot the nginx configuration we are temporarily changing this to backend to match with nginx upstream configuration
  name: backend
  labels:
    app: ask-me-ai
    tier: backend
spec:
  selector:
    app: ask-me-ai
    tier: backend
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  type: ClusterIP
