apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: ask-me-ai
    tier: nginx
spec:
  selector:
    app: ask-me-ai
    tier: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: http-alt
      port: 3000
      targetPort: 3000
  type: LoadBalancer
