apiVersion: v1
kind: Service
metadata:
  # name: redis-service
  # Ideally the name should be redis-service but inorder to troubleshoot the nginx configuration we are temporarily changing this to backend to match with nginx upstream configuration
  name: redis
  labels:
    app: ask-me-ai
    tier: redis
spec:
  selector:
    app: ask-me-ai
    tier: redis
  ports:
    - name: http
      port: 6379
      targetPort: 6379
  type: ClusterIP
